services:
  - type: web
    name: radio-terra
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    aptPackages:
      - ffmpeg
    envVars:
      - key: DISCORD_TOKEN
        sync: false
